networks:
  private-network:
    driver: overlay
    external: true

services:
  mariadb-svc:
    image: mariadb:${MARIADB_IMAGE_TAG:-latest}
    volumes:
      - "./db-init:/docker-entrypoint-initdb.d"
      - "/www/data/mysql-data:/var/lib/mysql"
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER:-}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-}
    networks:
      - private-network
    deploy:
      resources:
        limits:
          memory: 768M
        reservations:
          memory: 256M
      mode: replicated
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      labels:
        - "traefik.enable=false"
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any

  redis-svc:
    image: redis:${REDIS_IMAGE_TAG:-latest}
    command: redis-server --appendonly yes
    networks:
      - private-network
    deploy:
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 32M
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=false"
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
