networks:
  public-network:
    driver: overlay
    external: true

  private-network:
    driver: overlay
    external: true

services:
  your_app_name:
    image: tanngoc93/wordpress:latest
    working_dir: /usr/src/wordpress
    environment:
      # DATABASE SETUP
      WP_DB_HOST:          ${WP_DB_HOST}
      WP_DB_USER:          ${MARIADB_ROOT_USER}
      WP_DB_PASSWORD:      ${MARIADB_ROOT_PASSWORD}
      WP_DB_NAME:          ${WP_DB_NAME}
      WP_TABLE_PREFIX:     ${WP_TABLE_PREFIX}

      # REDIS SETUP
      WP_REDIS_HOST:       ${WP_REDIS_HOST}
      WP_REDIS_PORT:       ${WP_REDIS_PORT}
      WP_REDIS_DATABASE:   ${WP_REDIS_DATABASE}

      # Authentication unique keys and salts.
      #
      # Change these to different unique phrases! You can generate these using
      # the {@link https://api.wordpress.org/secret-key/1.1/salt/ WordPress.org secret-key service}.
      #
      # You can change these at any point in time to invalidate all existing cookies.
      # This will force all users to have to log in again.
      #
      # @since 2.6.0
      # 
      WP_AUTH_KEY:         ${WP_AUTH_KEY}
      WP_SECURE_AUTH_KEY:  ${WP_SECURE_AUTH_KEY}
      WP_LOGGED_IN_KEY:    ${WP_LOGGED_IN_KEY}
      WP_NONCE_KEY:        ${WP_NONCE_KEY}
      WP_AUTH_SALT:        ${WP_AUTH_SALT}
      WP_SECURE_AUTH_SALT: ${WP_SECURE_AUTH_SALT}
      WP_LOGGED_IN_SALT:   ${WP_LOGGED_IN_SALT}
      WP_NONCE_SALT:       ${WP_NONCE_SALT}

    volumes:
      - "./wp_appname:/usr/src/wordpress"
      - "./wp_appname/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=public-network"

        # Middleware: redirect
        - "traefik.http.middlewares.wp-appname-svc-redirect.redirectscheme.scheme=https"

        # HTTP Router
        - "traefik.http.routers.wp-appname-svc-http.rule=Host(`domain.com`) || Host(`www.domain.com`)"
        - "traefik.http.routers.wp-appname-svc-http.entrypoints=web"
        - "traefik.http.routers.wp-appname-svc-http.middlewares=wp-appname-svc-redirect"
        - "traefik.http.routers.wp-appname-svc-http.service=wp-appname-svc"

        # HTTPS Router
        - "traefik.http.routers.wp-appname-svc-https.rule=Host(`domain.com`)"
        - "traefik.http.routers.wp-appname-svc-https.entrypoints=websecured"
        - "traefik.http.routers.wp-appname-svc-https.tls.certresolver=myhttpchallenge"
        - "traefik.http.routers.wp-appname-svc-https.service=wp-appname-svc"

        # Service port
        - "traefik.http.services.wp-appname-svc.loadbalancer.server.port=80"
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
    networks:
      - private-network
      - public-network
